### ISSUE TITLE
Need a separate tab/weapon type for Mines

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#12]
Mines have no range.  Do we want to treat them as ranged weapons, but just leave Range and Ammo blank?

**Comment by honestaly** [comment]
Or do we use them as just ammo?  Now that ammo has a blast, damage, etc stats?

**Comment by TCArknight** [comment]
I added the WeaponCat.Mine tag for the next update, so we can give them that category and leave the Range and Ammo blank.
