### ISSUE TITLE
Ranged Weapon Nationality/Categories

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#14]
I'm not sure what I did wrong here, but after I added Swedish, Polish,, Soviet, etc weapons

The only categories that show up are Swedish and the Civilian ones and all other weapons are just listed under swedish.

**Comment by TCArknight** [comment]
I figured it out. :) 

When adding the new category for the weapons, need to add it in the tags.1st file as well. I made the WeaponCat group non-dynamic to force this for now. We can always go back later and make it dynamic for the user. However, if the new category doesn't have an entry in the tag group, then the order="x" entry for the category defaults to 0.
