### ISSUE TITLE
Loading a saved character generates a validation error

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#16]
For some reason Unarmed combat gets rechecked as if equipped when a character is loaded from a save.

I've unchecked the unarmed combat and on re-load it gets rechecked.

**Comment by TCArknight** [comment]
Fixed in next code update. 

items with the Equipment.Natural tag were automatically setting the grIsEquip value to 1. Now, it only does that if the item also has the Equipment.AutoEquip tag.
