### ISSUE TITLE
Character sheet output doesn't list all the relavent weapon stats

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#2]
i.e. the PDF for the character sheet has Reliability, ROF, Damage, Crit, Blast, Range, Mag, Armor, Weight, and Spent Ammo as entries 

Presently the Character sheet when print previewed only shows Range, Attack Value and Dmg.  It should be a page wide section with all of the relavant stats.

**Comment by TCArknight** [comment]
Done. Weapons section now matches all weapon stats.
