### ISSUE TITLE
LP mode Specialties "If you roll a specialty you already have, choose any"

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#24]
I was looking through the FL forums on T2K and ran into somebody mentioning this.  Since we're not creating an actual character generator, and expecting players to roll this stuff.  The general interpretation is that in LP mode   If you roll an existing specialty, you can choose any specialty.

![image](https://user-images.githubusercontent.com/88744339/130503065-6ed10e06-a165-4c56-b462-30fb8e727a86.png)

**Comment by honestaly** [comment]
https://forum.frialigan.se/viewtopic.php?f=127&t=8215

**Comment by TCArknight** [comment]
This is somewhat up in the air at the moment. We're not actually enforcing the roll for each module, so it's all pretty much up to the user to add what they've rolled. 

If we get to the fully 'rollable' version, we may have to look back at this. :)

**Comment by honestaly** [comment]
If we're allowing them to pick.  What about a list with the tour
specialties at the top, a divider and all specialties below it to support
that possibility?
