### ISSUE TITLE
Vehicle stats showing up in Character Output sheet

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#26]
![image](https://user-images.githubusercontent.com/88744339/132333537-6dc27219-191e-4984-8d74-68f5c9ab4cc3.png)

**Comment by honestaly** [comment]
And vice versa... Player stats show up on vehicles
![image](https://user-images.githubusercontent.com/88744339/132382598-2b8057cb-844d-4d51-b835-d01d490b2758.png)

**Comment by TCArknight** [comment]
Pushed fix for sheet

**Comment by honestaly** [comment]
Fixed for characters... needs some though for vehicles.

![image](https://user-images.githubusercontent.com/88744339/132793674-3ce1ed42-755b-4f08-adf5-4b963931f30f.png)

**Comment by TCArknight** [comment]
Ok, I think I have the Vehicle sheet fixed...
![image](https://user-images.githubusercontent.com/4914790/136626423-1d46f766-667e-42d1-af81-807ca35998ba.png)

**Comment by honestaly** [comment]
Somebody made a sheet that listed all the cargo stashed in the vehicle for the second column because... that's what PCs will do with a vehicle.

**Comment by honestaly** [comment]
Closing this and making a new card with vehicle issues.  Characters appear clean now
