### ISSUE TITLE
Latest Archetype update breaks lifepath creation

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#27]
Rolling attribute increases always seems to roll a 4, which is one problem that might just be randomness.  But spending 1 attribute increase point tells me I've overspent by 1

![image](https://user-images.githubusercontent.com/88744339/132615539-422b2fa4-6903-481f-83e5-1f79795e5912.png)

**Comment by TCArknight** [comment]
This should be fixed with the latest push. Try creating a new character as I've seen saved ones get totally out of whack when just refreshing... :)

**Comment by honestaly** [comment]
Nope, still has issues.
Archetypes cannot spend the 3 free points they get, as soon as they take anything above C it's overpsent.
Same thing happens with Lifepath.  They might have 4 points to spend, but they can't.
To be safe, I deleted my data files, and resynced with the latest and have the same issue.

![image](https://user-images.githubusercontent.com/88744339/132714481-2fb86da7-a4a8-4eb1-8bb9-c09836ef210f.png)
![image](https://user-images.githubusercontent.com/88744339/132714501-8a43a44e-1ef7-495d-9fd3-f56dd812a2c9.png)

**Comment by TCArknight** [comment]
Very Odd. :(

I just closed HL and reopened, creating new characters and it's doing fine for me:
![T2K LP Attrib](https://user-images.githubusercontent.com/4914790/132762427-5de29244-6ab0-4711-a506-5f4480757185.JPG)
![T2K LP Bonus Attrib](https://user-images.githubusercontent.com/4914790/132762428-8d8e74c4-11e1-478b-bada-58015dd5c411.JPG)
![T2K Arch Attrib](https://user-images.githubusercontent.com/4914790/132762429-a61cdd1b-ca9b-499e-b264-13342f00b270.JPG)

**Comment by honestaly** [comment]
Not here... it generates the points with a random roll... but when I use one it tells me I've overspent

**Comment by honestaly** [comment]
lol there was a new chunk of code I had to pull :)
