### ISSUE TITLE
Ammo picker display issue

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#29]
Posting this here because I took the ammo and added categories to it because there's so much of it now.
Added sorting, stuck in headers... and then I get this (similar to guns).

Any idea what causes it?  The names are correct, but they display with some kind of number over the top.

![image](https://user-images.githubusercontent.com/88744339/133091856-dfaf9ad3-c78a-4c32-8f31-83859b320a57.png)

**Comment by honestaly** [comment]
Found it... for some reason the display was showing the damage and crit ratings in the ammo displays... I simply removed them and made it clearner... exploring adding that info to the window to the right.

**Comment by honestaly** [comment]
Though for the life of me I can't find the code that makes that window on the right hand side when you click and item..  I've thought I found it 4 different times... but no luck yet.

**Comment by TCArknight** [comment]
Check the procedures.dat file for the descript procedure. I think this bit is where that part is coming in for ammo:
`~if this is a piece of gear, append proper info to the item-specific details
    if (tagis[component.Gear] <> 0) then

      ~call InfoConsumable

      ~append the item's weight
      iteminfo &= "Weight: "
      if (field[grWeight].value > 0) then
        ~ iteminfo &= field[grWeight].text & " each"
        iteminfo &= field[grWeight].text
      else
        iteminfo &= chr(150)
        endif
      iteminfo &= "{br}"
	  
      ~if this is a thing, append the cost
      if (ispick = 0) then
        iteminfo &= "Cost: " & splicetext[both, grcost, field[grCost].text] & "{br}"
	  else
        iteminfo &= "Value: " & splicetext[both, grcost, field[grTotalCost].text] & "{br}"
        endif

      endif`

**Comment by honestaly** [comment]
Yah I had remembered seeing that procedure before... but I couldn't find it.  Thanks.
That part above seems to be the generic portion for adding cost and weight to any item (or there's an equivalent for it)... so I added an AmmoInfo procedure to the file to handle Damage, Armor, Crit, Blast
