### ISSUE TITLE
Vehicles and Vehicle stats

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#3]
Vehicles are a complex mess.
A Vehicle has a reliability stat, which effectively determines the reliability for the following components:
Engine, Suspension, Wheels/Tracks, Radio

Other components that can be damaged include 
 Ammo (can be hit twice),
 Fuel (each hit reduces the current fuel capacity by half)
 Radio Antenna (Reliability 1)
 Fire Control system (Reliability 1)
 
 Individual Weapons (have their own base reliability and then ranged stats, some (like a commander's machinegun) can be easily removed and used separately from the vehicle, others (Tank Main Gun may not).
 
 Occupants of the vehicle take and receive damage as characters, but should be assigned a position within the vehicle as vehicles have a max capacity of internal passengers.

**Comment by TCArknight** [comment]
Yeah, vehicles are going to be a big thing... lol

**Comment by honestaly** [comment]
![image](https://user-images.githubusercontent.com/88744339/129089290-57954f37-b12e-4246-91a0-63f78b8ffcda.png)

**Comment by honestaly** [comment]
Closing to make a new card
