### ISSUE TITLE
Weapons Corrections

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#36]
1. When a firearm is loaded with ammo (i.e. ammo is stored in it) it should load an amount of ammunition equal to the magazine capacity less the current amount in it.  The total of that ammo in the character's backpack should be reduced by that amount.  This way multiple weapons that use the same ammo can share the source.

2. Weapons such as Mortars that load different kinds of ammo should properly change their damage stats to reflect what they have been loaded with.

**Comment by TCArknight** [comment]
Still investigating how to link the amounts. At moment, the weapons can select from what's on the character, but expenditures have to come from selling the ammo in between sessions to bring into sync.
