### ISSUE TITLE
Vehicle Corrections

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#37]
1. Vehicle stats have some display issues.    (see image)
2. Vehicles should not display skills on their characters sheet (see image)
3. Vehicles should not have stress (see image)
4. Vehicles take hits to components.  The components should show individual damage boxes in addition to the general vehicle reliability value.  Not all vehicles have all the same components.
5. Vehicles should allow for positions to be created (Commander, Driver, Gunner, Loader, Passenger) and characters assigned to those spots.  Not every vehicle will have all of those positions, and some vehicles may have multiples of Gunners, Loaders and/or Passengers.
6. Vehicles do not have Archetypes (but might have a class such as MBT, APC, etc), nor do they have Gender, Ages or Height or weight.
7. Vehicles should display their location armor values
8. Vehicles should be able to store cargo up to their cargo limit
9. Vehicles that take a hit to their fuel lose half of the onboard fuel.  This can happen any number of times, but would need to be tracked as each hit would require a separate repair.
10. Vehicles need to track both fuel capacity, and current fuel capacity

![image](https://user-images.githubusercontent.com/88744339/144312635-9e39227c-ab94-4138-8eb7-f0c5de07d7f1.png)
![image](https://user-images.githubusercontent.com/88744339/144313085-ec6b5b99-d998-4851-8744-f89f6a2bec5c.png)

**Comment by TCArknight** [comment]
Getting there on the output...

![image](https://user-images.githubusercontent.com/4914790/145256536-f3c5f2f6-ee35-402e-afab-117c2227e024.png)

**Comment by TCArknight** [comment]
Closing, split into several issues. :)
