### ISSUE TITLE
Defense and Initiative

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#4]
T2K Initiative is done by drawing cards from a deck.  There is no stat to influence it.  It should be rmeoved

Defense looks like a holdover from the original base ruleset from Hero lab and should also be removed

**Comment by TCArknight** [comment]
I don't want to remove them completely, because I believe they would be appropriate for other FL games like Forbidden Lands and Aliens. :) 

I'll see how we can hid them best.

**Comment by honestaly** [comment]
Glad I posted issues before I started tackling them.  I was going to pull Defense and Initiative out.

I haven't fully looked at Aliens yet, but I go the feeling it was more like T2K... and didn't use them either.

**Comment by honestaly** [comment]
Though Alien the RPG is based on Dice Pools.  It also just uses an initiative deck.
It's the only other FL game I'm really familiiar with.  But I suspect that many of these games won't readily convert directly to the others.

**Comment by TCArknight** [comment]
I think I initially started this with looking at Forbidden Lands before the T2K stuff was available, hence the couple of Primary/Secondary Archetype components. :)

I haven’t checked it in yet, but I’ve added a Hide.Trait tag that gets added to initiative and defense by the script on the Settings component. I’ve also added display of the Specialties on the Abilities tab (before the Skills). Oh yeah, and filtered Vehicles out of the Gear display on the character sheet and moved them to a dedicated entry on the 2nd page.

**Comment by honestaly** [comment]
Initiative and Defense are no longer visible, which is good enough. :)
