### ISSUE TITLE
Vehicle Character Sheets should not include PC stats

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#6]
A Vehicle character sheet print preview is effectively a PC's character sheet for the vehicle.

Vehicles do not have skills, nor do they have Strength, Agility, HIts, Stress, etc.

That said, there is no record form for a vehicle that was included with the game PDFs from the Kickstarter.
So we'll likely need to create our own. #3

**Comment by TCArknight** [comment]
Yep, I think we're on our own there.. I think someone has done one for Roll20 or Foundry, so we might can borrow some layout info, ideas there...

**Comment by honestaly** [comment]
Don't get too excited... but these are what I picked up in Foundry
![image](https://user-images.githubusercontent.com/88744339/129479346-3a86a4b3-50a6-4eea-8d09-362eb162268a.png)
![image](https://user-images.githubusercontent.com/88744339/129479349-9e6a7eae-7c60-4a32-9baf-26d1ebf852da.png)
![image](https://user-images.githubusercontent.com/88744339/129479363-f72288d3-d363-4bbb-a9d8-745ecae7af2a.png)
![image](https://user-images.githubusercontent.com/88744339/129479368-783a50b2-74b3-4f23-be73-c0fea200aff3.png)

**Comment by honestaly** [comment]
Now that Foundry has been released I'm updating the screen shots to show an M1A1
![image](https://user-images.githubusercontent.com/88744339/129955937-acdaaad1-7801-4bba-8fb9-73c9cb6afe42.png)
![image](https://user-images.githubusercontent.com/88744339/129955961-c85c3427-d0bb-41ff-98d7-3bedbdd95afe.png)
![image](https://user-images.githubusercontent.com/88744339/129955975-b2e2b76e-1ebc-4c21-ba14-5c440407b266.png)
![image](https://user-images.githubusercontent.com/88744339/129956000-9450f518-0dae-4476-9a15-a2bebaa9ff2e.png)
![image](https://user-images.githubusercontent.com/88744339/129956019-7c8482bf-e1f7-4e00-b3ba-f12853fba8a6.png)

**Comment by honestaly** [comment]
https://drive.google.com/file/d/1enQUCCzrCgOlb1Je8dhJm21JcwlREcOZ/view

**Comment by honestaly** [comment]
Closing
