### ISSUE TITLE
Syntax error in eval script for Component "Lifepath"

### ISSUE THREAD

**Issue by honestaly** [TCArknight/T2K4E#7]
Pulled the latest build... get a new error.

![image](https://user-images.githubusercontent.com/88744339/129089505-c3e801d2-a7e1-4ba4-9f51-e359f6e2f7fd.png)

**Comment by TCArknight** [comment]
Jush pushed the update which should take care of this. It seems to be something about that 'vbaDetails' issue that causes this.

**Comment by honestaly** [comment]
Issue appears resolved
